videojs/generator-videojs-plugin

- docs/standards.md
- src/app/package-json.js
- src/app/templates/_.npmignore
This makes it based on the generated `.gitignore` with the difference that build directories are _not_ ignored by NPM as they are needed for projects that depend on them.
> Fix npm packaging

- src/app/templates/test/_plugin.test.js
This resolves a whole class of possible tricky errors in tests by ensuring that `setTimeout` et al are mocked _before_ the player (and, importantly, any timers) gets created.
> Move clock mock before player creation

- fixtures/author/package.json
- package.json
- src/app/index.js
- src/test/app.test.js
This resolves the situation where an existing package.json has an author field, but it is an object instead of a string. In this case, the prompt is skipped.
Also includes some code cleanup that doesn't change behavior in any way.
Fixes #10
> Address author prompt from object

- docs/standards.md
- src/app/index.js
- src/app/package-json.js
- src/app/templates/_CONTRIBUTING.md
- src/app/templates/_README.md
- src/test/libs.js
- src/test/options.test.js
This makes things a bit smarter with default documentation generation.
- `README.md` is now focused on consumers of the generated plugin rather than plugin developers.
- `CONTRIBUTING.md` for open-source plugins is now focused on plugin developers.
> Documentation Tweaks

- src/app/package-json.js
This is a backward-compatible simplification of the `build:css` task and a bug fix for the incorrect `watch:css` task.
> Simplify build:css, fix watch:css.

- src/app/index.js
- src/app/templates/licenses/_apache2
- src/app/templates/licenses/_mit
- src/test/app.test.js
It turns out that a copyright doesn't need a year. This is easier than keeping it updated! 
Fixes #55
> Remove years from copyrights

- src/app/package-json.js
- src/app/templates/scripts/_server.js
- Throttle watch handler functions, so we don't trigger a bunch of builds and reloads when multiple files are changed at once.
- Make sure we bundle langs and Sass before starting server.
- For simplicity, bundle JS and tests when either changes.
- Do not watch `test/dist` file(s).
> Server Improvements

- src/app/templates/test/_karma.conf.js
As per the [documentation](https://karma-runner.github.io/0.13/config/plugins.html)
> By default, Karma loads all sibling NPM modules which have a name starting with karma-*.
So I have removed all references to plugins from the karma config as well as making the logic for wether to use detectBrowser simpler by using the enabled option.
> remove direct specification of karma plugins

- src/app/package-json.js
- src/app/templates/scripts/_server.js
There have been too many issues with generated code failing linting; so, rather than a bunch of patches to fix virtually pointless problems, let's just not lint the `scripts/` directory.
Fixes #77
> Don't lint scripts

- README.md
I repeatedly fail to remember whether the plugin is created in the current directory, or a directory is created (the former).
Adds a note to the readme to save (my) confusion.
> docs: Note that plugin is created in current directory

- generators/app/index.js
- generators/app/package-json.js
This outputs a boilerplate advanced plugin, if requested. Still defaults to a basic plugin.
> feat: Add prompt for selecting plugin type - basic (default) or advanced.

- generators/app/package-json.js
Sass only does a build when a file that it is watching changes, so there won't be an initial build. This PR makes an initial build happen
> fix: build sass before watching, as watch wont build until a change

- generators/app/package-json.js
we dont need to generate api docs every commit since they shouldn't be in the repo anyway
> fix: bring doc precommit from 5s to 1s

- generators/app/templates/scripts/_modules.rollup.config.js
The first build of js-modules passes, but subsequent builds fail due to a [bug in rollup that has yet to be resolved](https://github.com/rollup/rollup/issues/982). Since we don't bundle global in the module build anyway we can set it as external and stop the error from happening.
> fix: set global as external during watch, to prevent an error

- generators/app/package-json.js
`4.6.0` breaks watch
`4.5.3` is fine
https://github.com/sass/node-sass/issues/2139
> fix: broken watch as of sass 4.6.0

- generators/app/templates/test/_plugin.test.js
This reverts commit 87f0d08119a825098e944e37a20d95596306eae2.
> revert: fix: Tick 2ms in tests for player ready, see https://github.com/videojs/video.js/pull/4665 (#136)

- .travis.yml
- generators/app/templates/_.travis.yml
- generators/app/templates/_CONTRIBUTING.md
The `engine` field in `package.json` for running the generator indicates that generated projects require Node 4.8 or better, but this doesn't match the `CONTRIBUTING.md`.
Closes #135
> refactor: Make sure Node versions are consistent.

- generators/app/constants.js
- generators/app/index.js
- generators/app/package-json.js
- generators/app/templates/_index.html
- generators/app/templates/scripts/_modules.rollup.config.js
- generators/app/templates/scripts/_test.rollup.config.js
- generators/app/templates/scripts/_umd.rollup.config.js
- generators/app/templates/test/_index.html
- generators/app/templates/test/_karma.conf.js
- test/app.test.js
BREAKING CHANGE: Generated projects can no longer support IE8 out of the box.
> feat: Remove IE8 support option.

- docs/conventions.md
- generators/app/constants.js
- generators/app/index.js
- generators/app/package-json.js
- generators/app/templates/_index.html
- generators/app/templates/src/_plugin.scss
- generators/app/templates/test/_index.html
- generators/app/templates/test/_karma.conf.js
- test/app.test.js
- test/libs.js
BREAKING CHANGE: Generated projects no longer support Sass out of the box.
> feat: Remove Sass support option.

- README.md
Figured this would be useful as we go through and update a bunch of our projects.
> docs: Add some documentation on migrating to v7.

- generators/app/package-json.js
- package-lock.json
- package.json
Currently the generator is broken because a packages that try to install another packages will run the `postinstall` script on install. This tries to install `npm-merge-driver` and it is a `devDependency` so it will error out.
Fixes #227
> fix: use npm-merge-driver-install to fix install issues

- generators/app/package-json.js
- package-lock.json
- package.json
- scripts/run-integration-tests.js
Depends on https://github.com/videojs/videojs-generator-verify/pull/1
Closes #230
> feat: Use videojs-generator-verify to verify new packages

- generators/app/index.js
- generators/app/templates/_package-lock.json
- package.json
- scripts/generate-pkg-lock.js
- scripts/run-integration-tests.js
- test/libs.js
Generate a package lock for plugin to save ~70s on initial install, even when deps have changed by selecting other options.
> feat: generate package-lock for faster install

- generators/app/templates/_index.html
Setting `window.player` in index.html can mask some problems while testing in the browser, such as using `player` in a component instead of `this.player_`.
This uses `examplePlayer` instead.
> Use a different name for player in the test page

- plugin/package.json
The full problem is explained in [issues/266](https://github.com/videojs/generator-videojs-plugin/issues/266).
In short, `npm install` wasn't working since the dependecy `npm-run-all` was indirectly depending on `event-stream@3.3.6` which was removed from npm because of security reasons.
> Updated npm-run-all from 4.1.3 to 4.1.5 so that event-stream@3.3.6 not used.

- generators/app/templates/src/_plugin-basic.js
The dependency in package.json is `"^6 || ^7"` so the v5 compatiblity is unnecessary.
> fix: remove obsolete v5 compatiblity

- generators/app/generator.js
Initialise git in the dir, as otherwise the husky install fails.
Add an extra message before installing dependencies.
> feat: Init git in dir
