videojs/generator-videojs-plugin

app/templates/_package.json
Relates to https://github.com/dmlap/generator-videojs-plugin/issues/2
=> Added grunt to dev dependencies

src/app/index.js, src/test/options.test.js
=> Always use valid SPDX licenses

src/app/constants.js, src/app/index.js, src/app/package-json.js, src/app/templates/_README.md, src/app/templates/_bower.json, src/app/templates/_index.html, src/app/templates/scripts/_build-test.js, src/app/templates/scripts/_watch-test.js, src/app/templates/src/_plugin.js, src/app/templates/src/_plugin.scss, src/app/templates/test/_index.html, src/app/templates/test/_plugin.test.js, src/app/templates/test/karma/_common.js, src/app/validators.js, src/test/app.test.js
Pretty self-explanatory. Also, some related code cleanup and efforts toward DRYness. 
Fixes #40
=> Add scoped package support

src/app/index.js, src/app/package-json.js
Ignore the branch name, it does something different now :grin:
=> ghooks pre-push npm test

README.md, src/app/index.js, src/test/libs.js, src/test/options.test.js
Fixes #67. This adds the `--limit-to` and `--limit-to-meta` options.
=> Add limit-to and limit-to-meta options

src/app/package-json.js, src/app/templates/scripts/_build-test.js, src/app/templates/scripts/_server.js
Fixes #58 and #70 and issues with using generated plugins as a dependency of a project.
=> Only browserify-shim dist files

README.md, src/app/index.js, src/app/package-json.js
It doesn't make a ton of sense for "test" to be the default and only option for ghooks. This adds "lint" as another option (the default as well) and allows the user to choose "none".
Fixes #73
=> Make ghooks have options (including off)

README.md, src/app/index.js, src/app/package-json.js, src/app/templates/_jsdoc.json, src/test/libs.js
=> add jsdoc markdown support

package.json, src/app/index.js, src/app/package-json.js, src/app/templates/_.babelrc, src/test/app.test.js, src/test/libs.js
* re-generated README table of contents
* updated babel to babel 6
=> update to babel 6

package.json, src/app/package-json.js, src/test/app.test.js
This change fixes a potential issue when generating a new project and selecting "none" for the ghooks option. It will cause an error to be thrown because the key does not exist. This causes the project to fail to generate.
=> Fix a possible delete property error

src/app/package-json.js, src/app/templates/scripts/_version.js
=> Do not update CHANGELOG for prereleases

src/app/generator-version.js, src/app/package-json.js, src/test/app.test.js
=> Add generator-version

src/app/package-json.js
=> only include useful files on npm

src/check/package-json.test.js, src/check/structure.test.js
Tested and working.
Also, this includes the commit from #100 - so, only review changes to files in `src/check/`.
=> videojs-plugin-check Updates for v3

src/app/templates/_.travis.yml, src/app/templates/src/_plugin.js, src/app/templates/test/_karma.conf.js, src/app/templates/test/_plugin.test.js
This updates the generator v2 to output a plugin that works with both Video.js 5 and 6. This has been tested and verified.
A subsequent PR will be opened to allow outputting an advanced plugin instead of a basic one.
=> Video.js 5/6 cross-compatibility

generators/app/templates/_index.html
=> fix: Fix an issue in generated index.html paths as well as making all paths relative, which helps with GitHub Pages and other uses.

bin/videojs-generator-cleanup.js, generators/app/package-json.js, test/app.test.js
I don't think this is a major version bump, as it shouldn't actually break anything.
=> use husky instead of ghooks

generators/app/templates/_README.md, generators/app/templates/_bower.json, generators/app/templates/docs/_index.md, generators/app/templates/licenses/_apache2, generators/app/templates/licenses/_mit, generators/app/templates/src/css/_index.scss, generators/app/templates/src/js/_index-advanced.js, generators/app/templates/src/js/_index-basic.js, generators/app/templates/test/_index.test.js
=> fix: Fixes #116, remove HTML escaping for non-HTML files.

generators/app/templates/test/_plugin.test.js
https://github.com/videojs/video.js/pull/4665
=> fix: tick 2 for player ready

generators/app/package-json.js
See https://www.npmjs.com/package/in-publish
=> feat: don't build on install

generators/app/templates/_.gitignore
=> fix: Do not add .yo-rc.json to .gitignore

.travis.yml, package-lock.json, package.json
Closes #163, Closes #167, Closes #157
=> chore(package): update deps from greenkeeper prs

generators/app/templates/scripts/_rollup.config.js
make the rollup config more user-editable
=> Refactor: better rollup

generators/app/index.js
=> fix: do not exit on unlicensed

generators/app/templates/scripts/_rollup.config.js
In some projects is necessary to add build targets, with the current config there is a lot of boilerplate involved in doing that. This pr 
* trims down the config overall
* Removes some of the build specific plugin variables in favor of using `filter` and `concat`
* Adds build names into the code (even though they won't be used) so that it is much easier to copy a specific build and make changes if that is needed.
=> refactor: refactor the rollup config for easier build additions

package-lock.json, package.json
=> Greenkeeper/cssnano 4.0.3

package-lock.json, package.json
=> Greenkeeper/rollup 0.63.2

generators/app/package-json.js, generators/app/templates/scripts/_postcss.config.js, package.json
See https://github.com/videojs/videojs-generate-postcss-config/pull/1
=> feat: simplify postcss config

.gitignore, generators/app/templates/_.gitignore, package-lock.json, package.json
=> feat: update vjsstandard

.travis.yml, generators/app/templates/_.travis.yml
Use cache in travis to speedup install
=> feat: use cache in travis

.travis.yml, generators/app/templates/_.travis.yml, package-lock.json, plugin/package-lock.json
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
=> chore: update travis config per recommendations

package-lock.json, package.json, scripts/run-integration-tests.js
* Makes test/commands being run more apparent
* Adds a debug mode that should always run in ci
* Now verifies:
* linting on commit
* that doctoc works
* that npm-merge-driver works
* that the changelog tool works
* that the automated release process and publish process work
=> tests: Improve the integration test script

plugin/package-lock.json, plugin/package.json
Closes videojs/generator-videojs-plugin#283
=> Greenkeeper/default/videojs generate rollup config 3.2.0

generators/app/templates/_CONTRIBUTING.md
Following #307, update CONTRIBUTING to match
=> fix: Update contributing template for node 14
